In [1]:
import torch
A=torch.tensor([
    [1,-2],
    [3,2]
],dtype=float)
# Định thức ma trận A, ký hiệu|A|
torch.det(A)

tensor(8., dtype=torch.float64)

Ma trận nghịch đảo

In [11]:
I=A@torch.linalg.inv(A) # A@A^-1 = Ma trận đơn vị n cấp ký hiệu In

tensor([[1., 0.],
        [0., 1.]], dtype=torch.float64)

In [7]:
B=torch.tensor([
    [1,2,1],
    [2,3,4],
    [2,1,2]
],dtype=float)
torch.det(B)

tensor(6., dtype=torch.float64)

In [13]:
B@torch.linalg.inv(B)

tensor([[ 1.0000e+00,  1.1102e-16, -2.7756e-17],
        [ 0.0000e+00,  1.0000e+00,  1.1102e-16],
        [ 0.0000e+00,  0.0000e+00,  1.0000e+00]], dtype=torch.float64)

Tích hadamard  2 ma trận:  A*B. 
<br/>Lưu ý: 2 ma trận phải cùng kích thước mới có thể thực hiện phép cộng, trừ, tích hadamard

Tích thông thường cần ma trận A có kích thước m x n và ma trận B có kích thước n x p mới có thể thực hiện phép tính: A@B và phép nhân này không có tính chất giao hoán <br/>
Kết quả cho ra ma trận C có kích thước m x p

In [14]:
A=torch.tensor([
    [1,2],
    [0,1]
],dtype=float)
B=torch.tensor([ 
    [1,2],
    [5,-3]
],dtype=float)
torch.linalg.inv(A)@(B-A@A)

tensor([[-10.,   6.],
        [  5.,  -4.]], dtype=torch.float64)

In [15]:
torch.linalg.inv(A)@B-A

tensor([[-10.,   6.],
        [  5.,  -4.]], dtype=torch.float64)

<h3>Mệnh đề</h3>
Hạng của một ma trận không thay đổi khi ta áp dụng các phép biến đổi sơ cấp lên ma
trận đó

In [21]:
A=torch.tensor(
    [[1 ,1, 1, 1, 1],
    [2, 1, 2, 1, 1],
    [3, 4, 2, 1, 2],
    [4, 4, 3, 1, 2]],dtype=float
)
torch.matrix_rank(A) #Hạng của ma trận

tensor(3)

Một xí nghiệp sản xuất ra 3 loại sản phẩm G1, G2, G3 và phân phối hàng tuần cho 3
đại lý A, B, C với số lượng cho bởi bảng sau <br/>
G1 G2 G3<br/>
Đại lý A 150 320 180<br/>
Đại lý B 170 420 190<br/>
Đại lý C 201 63 58<br/>
Giả sử giá nhập các sản phẩm G1, G2, G3 lần lượt là 480$, 600$, 1020$. Và giá bán lẻ
của các sản phẩm tại các đại lý phân phối cho bởi bảng sau<br/>
         G1 G2 G3<br/>
Đại lý A 560 750 1580<br/>
Đại lý B 520 690 1390<br/>
Đại lý C 590 720 1780<br/>

In [26]:
Q=torch.tensor(
    [
        [150,320,180],
        [170,420,190],
        [201,63,58]
    ],dtype=float
)
C=torch.tensor([
    [480,600,1020]
],dtype=float)
P=torch.tensor([
    [560,750,1580],
    [520,690,1390],
    [590,720,1780]
],dtype=float)

Tính chi phí hàng tuần của mỗi đại lý

In [37]:
CP=Q@C.T
CP

tensor([[447600.],
        [527400.],
        [193440.]], dtype=torch.float64)

Tính tổng doanh thu hàng tuần của mỗi đại lý đối với từng loại hàng hóa

In [34]:
Q*P

tensor([[ 84000., 240000., 284400.],
        [ 88400., 289800., 264100.],
        [118590.,  45360., 103240.]], dtype=torch.float64)

Tính tổng doanh thu hàng tuần của mỗi đại lý
Tổng doanh thu của mỗi cửa hàng nằm trên đường chéo chính của ma trận dưới đây

In [35]:
Q@P.T

tensor([[608400., 549000., 639300.],
        [710400., 642300., 740900.],
        [251450., 228610., 267190.]], dtype=torch.float64)

Tính tổng lợi nhuận hàng tuần của mỗi đại lý.

In [61]:
Revenue=torch.sum(Q*P,1,keepdim =True)

In [63]:
Revenue-CP

tensor([[160800.],
        [114900.],
        [ 73750.]], dtype=torch.float64)